# Version of the configuration file
version: 5.1.0
variant: default
logo: /images/logo.svg

# ===== 头部配置优化 =====
head:
  favicon: /images/favicon.svg
  meta:
    - 'name=theme-color;content=#ffffff'  # 示例有效meta配置
  rss: /atom.xml  # 启用RSS需先安装hexo-generator-feed

# ===== 导航栏配置 =====
navbar:
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
  links:
    GitHub仓库:
      icon: fab fa-github
      url: 'https://github.com/GaryByd/Gary.github.io'
  search:
    # Name of the search plugin
    type: insight
  

# ===== 页脚配置 =====
footer:
  copyright: '© 2023-2025 GaryByd'
  links:
    CC协议:
      icon: fab fa-creative-commons
      url: 'https://creativecommons.org/licenses/by/4.0/'

# ===== 文章配置 =====
article:
  excerpt:
    length: 100 # 这里设置摘要长度，单位是字符: 100
  thumbnail: true     # 是否显示文章缩略图
  highlight:
    theme: atom-one-dark  # 更改为深色主题
    clipboard: true
  licenses:
    CC-BY-NC:
      icon: fab fa-creative-commons-nc
      url: 'https://creativecommons.org/licenses/by-nc/4.0/'
   
     
# ===== 侧边栏组件修复 =====
widgets:
  # 个人资料组件
  - position: left
    type: profile
    author: Gary
    author_title: 保持一份热爱，奔赴下一场火海
    avatar: /images/avatar.png
    avatar_rounded: true
    location: China,JiangXi
    social_links:
      GitHub:
        icon: fab fa-github
        url: 'https://github.com/GaryByd'

    # 分类组件
  - position: left
    type: categories
      
  - position: right
    type: toc
    index: true
    show_on: post
    # 最新文章
  - position: right
    type: recent_posts

    # 项目链接
  - position: right
    type: links
    links:
      爬虫实例: https://github.com/GaryByd/Crawler_instances
      RSM微信版: https://github.com/GaryByd/RSM_WeChat_Version
    # 归档
  - position: left
    type: archives

    # 标签云（关键修复）
  - position: right
    type: tags
    order_by: name
    amount: 15  # 必须指定显示数量
    show_count: true
    
# ===== 其他插件配置 =====
plugins:
  back_to_top: true

# ===== 分享插件激活 =====
share:
  type: sharethis
  install_url: 'https://platform-api.sharethis.com/js/sharethis.js#property=你的ID'

# ===== 性能优化 =====
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
