title: GaryHome
post_asset_folder: true
toc:
  enable: true
  number: true # 目录前面加序号
  list_number: true # 多级编号
avatar:
  url: /images/avatar.jpg
  width: 128px
  height: 128px
  rounded: true
search:
  type: insight  # 启用 Insight 搜索
  path: search.json  # 生成的 JSON 路径
  field: post  # 只搜索文章（可以改成 all 搜索所有内容）
subtitle: 技术探索与生活随笔
description: Gary的技术博客，分享Web开发、云原生与工具链实践
keywords:
  - 前端开发
  - 云原生
  - DevOps
  - 技术博客
author: Gary Byd
author_title: 全栈开发者
language: zh-CN
timezone: Asia/Shanghai
markdown:  
  anchors:  
    level: 3     # 生成锚点的标题层级  
    collisionAvoidance: 'wrap'  
social_links:
  - name: Zhihu
    url: https://github.com/GaryByd
    icon: fab fa-zhihu
url: https://garybyd.github.io/
permalink: posts/:title/
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
new_post_name: ':title.md'
default_layout: post
highlight:
  line_number: true
  auto_detect: true
  hljs: true
deploy:
  type: git
  repo: https://github.com/GaryByd/Gary.github.io.git
  branch: main
  message: 'Site updated: {{ now(''YYYY-MM-DD HH:mm:ss'') }}'
theme: icarus
abbrlink:
  alg: crc32
  rep: hex
